### ISSUE TITLE
getting TypeError: Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by japaveh** [cometchat-pro/javascript-react-chat-app#41]
### Describe the problem

> When I download the quickstart and run yarn install and start the application and go to the conversion-list I get the following error TypeError: Cannot read property 'theme' of undefined

![image](https://user-images.githubusercontent.com/1028237/124154368-b82ef700-da95-11eb-84ad-e1c5d60a8de5.png)

### What was the expected behavior?

I expect to see a list of conversations

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

It occurs in the v2 and v3 app

U use the default chat app and only change the values in consts.js to the correct values

**Comment by priyadarshininadar** [comment]
This is fixed in [https://github.com/cometchat-pro/cometchat-pro-react-ui-kit/releases/tag/v2.3.6-3](https://github.com/cometchat-pro/cometchat-pro-react-ui-kit/releases/tag/v2.3.6-3)
